import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this app
*/
`;
const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
    css: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "dest/main.js",
  format: "esm",
  sourcemap: prod ? false : true,
  platform: "browser",
  minify: true,
  target: ["es2020"],
  logLevel: "info",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
