import esbuild from "esbuild";
import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this app
*/
`;
const prod = process.argv[2] === "production";
const buildTarget = process.env.APP_TARGET || "web";
const enableExternalPlugins = process.env.ENABLE_EXTERNAL_PLUGINS === "true";

if (!["web", "electron", "capacitor"].includes(buildTarget)) {
  throw new Error(`Unsupported APP_TARGET: ${buildTarget}`);
}

function writeMetadata() {
  const targetVersion = process.env.npm_package_version;
  let ServiceWorkerFile = readFileSync("src/web/service-worker.js", "utf8").split("\n");
  ServiceWorkerFile[0] = `const VERSION = "${targetVersion}";`;
  writeFileSync("src/web/service-worker.js", ServiceWorkerFile.join("\n"));

  const mymetadata = {
    name: "Touch Grass Bible",
    description:
      "The bible app that keeps you grounded in the word while letting you into some functionality.",
    version: targetVersion,
    build: new Date().toISOString(),
    author: "Justice Vellacott",
    license: "MIT",
  };
  writeFileSync("src/info.json", JSON.stringify(mymetadata, null, 2));
}

/**
 * Generates `dist/index.html` from the web template, conditionally injecting
 * a Content Security Policy meta tag based on the build mode.
 *
 * - Secure build (`ENABLE_EXTERNAL_PLUGINS=false`): strict CSP that disallows
 *   eval and blob: script sources.
 * - Extensible build (`ENABLE_EXTERNAL_PLUGINS=true`): relaxed CSP that
 *   permits `blob:` script sources and `unsafe-eval` required for dynamic
 *   plugin evaluation.
 */
function writeIndexHtml() {
  const template = readFileSync("src/web/index.html", "utf8");

  const cspContent = enableExternalPlugins
    ? "default-src 'self'; script-src 'self' 'unsafe-eval' blob:; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; worker-src blob:;"
    : "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;";

  const cspMetaTag = `    <meta http-equiv="Content-Security-Policy" content="${cspContent}" />`;

  const output = template.replace(
    /(<meta\s+charset\s*=\s*"UTF-8"\s*\/>)/i,
    `$1\n${cspMetaTag}`,
  );

  writeFileSync("dist/index.html", output);
}

// Always write metadata before starting
writeMetadata();

const context = await esbuild.context({
  banner: {
    js: banner,
    css: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "dist/main.js",
  metafile: prod,
  format: "iife",
  sourcemap: prod ? false : true,
  platform: "browser",
  logLevel: "info",
  minify: prod,
  treeShaking: true,
  define: {
    __ENABLE_EXTERNAL_PLUGINS__: JSON.stringify(enableExternalPlugins),
  },
  plugins: [
    {
      name: "metadata-writer",
      setup(build) {
        build.onStart(() => writeMetadata());
      },
    },
    {
      name: "platform-virtual-module",
      setup(build) {
        build.onResolve({ filter: /^@platform$/ }, () => ({
          path: `@platform/${buildTarget}`,
          namespace: "tg-platform",
        }));

        build.onLoad({ filter: /.*/, namespace: "tg-platform" }, () => ({
          contents: [
            `export { createPlatformBridge } from "./${buildTarget}.ts";`,
            'export type { PlatformBridge, PlatformFileAdapter, PlatformStorageAdapter, PlatformTarget } from "./types.ts";',
          ].join("\n"),
          loader: "ts",
          resolveDir: resolve("src/platform"),
        }));
      },
    },
  ],
});

if (prod) {
  const result = await context.rebuild();

  // Write processed index.html with appropriate CSP
  writeIndexHtml();

  // 3. Write the metafile to disk
  if (result.metafile) {
    writeFileSync("meta.json", JSON.stringify(result.metafile, null, 2));
    console.log("Analysis metafile generated: meta.json");
  }

  console.log(`Built target: ${buildTarget} (external plugins: ${enableExternalPlugins})`);

  process.exit(0);
} else {
  await context.watch();
}
