import esbuild from "esbuild";
import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this app
*/
`;
const prod = process.argv[2] === "production";
const buildTarget = process.env.APP_TARGET || "web";

if (!["web", "electron", "capacitor"].includes(buildTarget)) {
  throw new Error(`Unsupported APP_TARGET: ${buildTarget}`);
}

function writeMetadata() {
  const targetVersion = process.env.npm_package_version;
  let ServiceWorkerFile = readFileSync("src/web/service-worker.js", "utf8").split("\n");
  ServiceWorkerFile[0] = `const VERSION = "${targetVersion}";`;
  writeFileSync("src/web/service-worker.js", ServiceWorkerFile.join("\n"));

  const mymetadata = {
    name: "Touch Grass Bible",
    description:
      "The bible app that keeps you grounded in the word while letting you into some functionality.",
    version: targetVersion,
    build: new Date().toISOString(),
    author: "Justice Vellacott",
    license: "MIT",
  };
  writeFileSync("src/info.json", JSON.stringify(mymetadata, null, 2));
}

// Always write metadata before starting
writeMetadata();

const context = await esbuild.context({
  banner: {
    js: banner,
    css: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "dist/main.js",
  metafile: prod,
  format: "iife",
  sourcemap: prod ? false : true,
  platform: "browser",
  logLevel: "info",
  minify: prod,
  treeShaking: true,
  plugins: [
    {
      name: "metadata-writer",
      setup(build) {
        build.onStart(() => writeMetadata());
      },
    },
    {
      name: "platform-virtual-module",
      setup(build) {
        build.onResolve({ filter: /^@platform$/ }, () => ({
          path: `@platform/${buildTarget}`,
          namespace: "tg-platform",
        }));

        build.onLoad({ filter: /.*/, namespace: "tg-platform" }, () => ({
          contents: [
            `export { createPlatformBridge } from "./${buildTarget}.ts";`,
            'export type { PlatformBridge, PlatformFileAdapter, PlatformStorageAdapter, PlatformTarget } from "./types.ts";',
          ].join("\n"),
          loader: "ts",
          resolveDir: resolve("src/platform"),
        }));
      },
    },
  ],
});

if (prod) {
  const result = await context.rebuild();

  // 3. Write the metafile to disk
  if (result.metafile) {
    writeFileSync("meta.json", JSON.stringify(result.metafile, null, 2));
    console.log("Analysis metafile generated: meta.json");
  }

  console.log(`Built target: ${buildTarget}`);

  process.exit(0);
} else {
  await context.watch();
}
